%YAML:1.0
---
# ===================================================================================
# VINS-Fusion Camera Intrinsic File
# ===================================================================================
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
  k1: -0.037957623173092134
  k2: -0.009063100478713382
  p1: 0.0032499387935820225
  p2: -0.0026421156858246362
projection_parameters:
  fx: 546.4796293924256
  fy: 546.865121933073
  cx: 318.2431443468248
  cy: 242.98292743820704
